### PR TITLE
Csla4

### PR DESCRIPTION
**Pull request by jasona22**
Hope I am doing this right.  I've never used this tool before.  Dates make this feel really old and not current.  Anyhow, doing a CSLA project and need latest CSLA templates.  Using VS2015, current .net and SQL Server.  Not sure what else I am supposed to put into this pull request.

### CODE REVIEW

**Comment by jasona22** [comment]
NO!  I don't want ot merge anything.  I want to pull the latest templates.  This github stuff stinks.

**Comment by niemyjski** [comment]
You'll just need to click the download button or clone button on the main page of GitHub. Please feel free to submit any updates to the templates.

**Comment by niemyjski** [comment]
Also, the latest templates are in master.

**Comment by jasona22** [comment]
Yea, I was in Master.  I didn't want every framework and project and when I
drilled down the "Clone and Download" vanished.  HOWEVER, I figured out not
to drill down but use the drop down.  That's clear!  (not your fault; just
annoyed at bad interfaces and I feel Git has bad interfaces).

My exasperation aside, I am clearly doing something else wrong.  I pulled
the CSLA project down and it will not compile.  The odd thing about it is I
have like 380 errors.  But as I select each error to get an idea of what
the problem is, the red squiggles vanish and the error count goes down.  I
can continue looking at each error in turn until the entire project says  0
errors.  Then rebuild and have 380 again.  Kind of makes me think of the 99
bugs in the code song.   I don't really think  there are bugs, but the
behavior is rather odd.  I don't see any NuGet packages.  Any experience
with this behavior?  None of the references are complaining.

Thanks in advance.

J

**Comment by niemyjski** [comment]
I don't think anything should be reaching out to team services. My only thought is when you try to generate in project that's tied to source control we call api's to try and check out those files. Yes, some work needs to be done for the new visual studios. In Generator 8 we broke it by moving to a generate on build based nuget package so the targets file is no longer there. AdoHelper is a template that gets rendered.

**Pull request closed without merging**
